add feature to ignore blur event when debugging
benwinding/command-pal pull request #26
Opened 2023-02-04 20:06 UTC by rouilj

If the command palette is open, switching to devtools closes the palette.  This makes debugging difficult. This adds the ability to ignore the blur event by setting window.commandPalIgnoreBlur = true in the devtools console or script block in an html page.

It's a dev only tool that I have found useful in debugging/enhancing command-pal.

2023-02-05 23:23 UTC, benwinding requested changes
Great idea, I just don't think it should use `window`

2023-02-05 23:23 UTC, benwinding commented on src/SearchField.svelte
> +    if (window.commandPalIgnoreBlur) return;
I would prefer this be passed in as an option to the class, rather than a global var on `window` 🤔

2023-02-06 00:51 UTC, rouilj commented on src/SearchField.svelte
> +    if (window.commandPalIgnoreBlur) return;
I almost agree with you, but consider this case. Some random user is using an app that uses command-pal.
It doesn't work. The layout is wonky etc. What can that user do to fix the issue or generate info to allow the developers to fix it?

The CommandPal call is somewhere in minimized javascript. The end user may not be able to
change/reinvoke/find out how its called. So they won't be able to debug it at all.

This mechanism allows any user (really developer but not of the app they are trying to debug) who knows
the magic word) to debug the html and try to figure out what happened.

I agree on not polluting the window namespace. I am not sure if that every deployment of command-pal will define window.CommandPal. If it does we can move the setting from window to window.CommandPal.
It's still not a CommandPal option (since you would never run in production with it) but it won't pollute the namespace.

To produce the hashes, I also considered setting a variable using javascript rather than using an option.
Arguably a remote dev could figure out that the CSP hashes were wrong. But I think (perhaps incorrectly) that it is less likely to break than the html/css.

Thoughts?

2023-02-06 15:05 UTC, benwinding commented on src/SearchField.svelte
> +    if (window.commandPalIgnoreBlur) return;
Thanks for the explanation, I see what you mean now, it's actually a bit cumbersome to work on, when in the dev-tools and it's constantly `blur()`ing and disappearing. I'm convinced 👌

2023-02-06 15:05 UTC, benwinding approved these changes

2023-02-06 15:05 UTC, merged

2023-02-06 15:07 UTC, rouilj commented
There may be a better way of suppressing the blur handler using DevTools. I guess you could unbind the event
handler if you knew how.